// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pggasaonepyuqnmnowsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnZ2FzYW9uZXB5dXFubW5vd3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODk3OTEsImV4cCI6MjA3MTQ2NTc5MX0.PihpUx4RYfR4ckf1c05q5v0X3C3woZUJQhSDZdVLFx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});